version: '2'
services:
  nginx:
    image: nginx:stable
    ports: 
      - "8080:80"
    volumes:
      - ./drupal:/drupal
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    image: php:7.0-fpm
    volumes:
      - ./drupal:/drupal